export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_ID: 'INVALID_ID',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  FORBIDDEN: 'FORBIDDEN',
  EMPLOYEE_PROFILE_REQUIRED: 'EMPLOYEE_PROFILE_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  EMPLOYEE_EMAIL_TAKEN: 'EMPLOYEE_EMAIL_TAKEN',
  EMPLOYEE_NUMBER_TAKEN: 'EMPLOYEE_NUMBER_TAKEN',
  ATTENDANCE_ALREADY_SUBMITTED: 'ATTENDANCE_ALREADY_SUBMITTED',
  NOT_CHECKED_IN: 'NOT_CHECKED_IN',
  ALREADY_CHECKED_OUT: 'ALREADY_CHECKED_OUT',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  CANNOT_DEACTIVATE_SELF: 'CANNOT_DEACTIVATE_SELF',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
